apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: cicd-demo-api-pipeline
metadata:
  annotations:
    description: 3scale API publishing Pipeline
  name: cicd-demo-api-pipeline
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: cicd-demo-api-pipeline
    name: cicd-demo-api-pipeline
  spec:
    output: null
    postCommit: null
    resources: null
    runPolicy: Serial
    source:
      type: None
    source:
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_BRANCH}
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: cicd/Jenkinsfile
        env:
        - name: GIT_BRANCH
          value: ${GIT_BRANCH}
        - name: GIT_REPO
          value: ${GIT_REPO}
        - name: DEV_PRIVATE_BASE_URL
          value: ${DEV_PRIVATE_BASE_URL}
        - name: TEST_PRIVATE_BASE_URL
          value: ${TEST_PRIVATE_BASE_URL}          
        - name: PROD_PRIVATE_BASE_URL
          value: ${PROD_PRIVATE_BASE_URL}
        - name: DEV_PRODUCTION_PUBLIC_BASE_URL
          value: ${DEV_PRODUCTION_PUBLIC_BASE_URL}
        - name: DEV_STAGING_PUBLIC_BASE_URL
          value: ${DEV_STAGING_PUBLIC_BASE_URL}
        - name: TEST_PRODUCTION_PUBLIC_BASE_URL
          value: ${TEST_PRODUCTION_PUBLIC_BASE_URL}
        - name: TEST_STAGING_PUBLIC_BASE_URL
          value: ${TEST_STAGING_PUBLIC_BASE_URL}
        - name: PROD_PRODUCTION_PUBLIC_BASE_URL
          value: ${PROD_PRODUCTION_PUBLIC_BASE_URL}
        - name: PROD_STAGING_PUBLIC_BASE_URL
          value: ${PROD_STAGING_PUBLIC_BASE_URL}
        - name: API_BASE_SYSTEM_NAME
          value: ${API_BASE_SYSTEM_NAME}
        - name: DEV_PROJECT
          value: ${DEV_PROJECT}
        - name: TEST_PROJECT
          value: ${TEST_PROJECT}
        - name: PROD_PROJECT
          value: ${PROD_PROJECT}
        - name: IMAGE_NAMESPACE
          value: ${IMAGE_NAMESPACE}
        - name: SECRET_NAME
          value: ${SECRET_NAME}
        - name: TARGET_INSTANCE_DEV
          value: ${TARGET_INSTANCE_DEV}
        - name: TARGET_INSTANCE_TEST
          value: ${TARGET_INSTANCE_TEST}
        - name: TARGET_INSTANCE_PROD
          value: ${TARGET_INSTANCE_PROD}
        - name: DEV_DEVELOPER_ACCOUNT_ID
          value: ${DEV_DEVELOPER_ACCOUNT_ID}
        - name: TEST_DEVELOPER_ACCOUNT_ID
          value: ${TEST_DEVELOPER_ACCOUNT_ID}
        - name: PROD_DEVELOPER_ACCOUNT_ID
          value: ${PROD_DEVELOPER_ACCOUNT_ID}
        - name: DISABLE_TLS_VALIDATION
          value: ${DISABLE_TLS_VALIDATION}
        - name: APPLICATION_NAME
          value: ${APPLICATION_NAME}
        - name: OPENAPI_SPECIFICATION_FILE
          value: ${OPENAPI_SPECIFICATION_FILE}
        - name: TOOLBOX_IMAGE_REGISTRY
          value: ${TOOLBOX_IMAGE_REGISTRY}
parameters:
- name: GIT_REPO
  value: https://github.com/lucamaf/telefonica.git
  required: true
- name: GIT_BRANCH
  value: master
  required: true
- name: DEV_PRIVATE_BASE_URL
  required: true
  value: 'http://echo-api.3scale.net'
- name: TEST_PRIVATE_BASE_URL
  required: false
- name: PROD_PRIVATE_BASE_URL
  required: false
- name: DEV_PRODUCTION_PUBLIC_BASE_URL
  value: 'https://api-3scale-apicast-production.apps.telefonica.c1u7.p1.openshiftapps.com'
  required: true
- name: DEV_STAGING_PUBLIC_BASE_URL
  value: 'https://api-3scale-apicast-staging.apps.telefonica.c1u7.p1.openshiftapps.com'
  required: true
- name: TEST_PRODUCTION_PUBLIC_BASE_URL
  value: 'https://oapi-p-v3-test.api.5.9.49.249.xip.io'
  required: true
- name: TEST_STAGING_PUBLIC_BASE_URL
  value: 'https://oapi-s-v3-test.api.5.9.49.249.xip.io'
  required: true  
- name: PROD_PRODUCTION_PUBLIC_BASE_URL
  value: 'https://oapi-p-v3-prod.api.5.9.49.249.xip.io'
  required: true
- name: PROD_STAGING_PUBLIC_BASE_URL
  value: 'https://oapi-s-v3-prod.api.5.9.49.249.xip.io'
  required: true
- name: API_BASE_SYSTEM_NAME
  value: my_api
  required: true
- name: DEV_PROJECT
  required: true
  value: DEV
- name: TEST_PROJECT
  required: false
  value: TEST
- name: PROD_PROJECT
  required: false
  value: PROD
- name: IMAGE_NAMESPACE
  required: true
  value: appdev-jenkins
- name: SECRET_NAME
  value: 3scale-toolbox
  required: true  
- name: TARGET_INSTANCE_DEV
  value: acme
  required: true  
- name: TARGET_INSTANCE_TEST
  value: test
  required: false
- name: TARGET_INSTANCE_PROD
  value: hetzner
  required: false
- name: DEV_DEVELOPER_ACCOUNT_ID
  required: true
  value: "3"
- name: TEST_DEVELOPER_ACCOUNT_ID
  required: false
  value: "2445581796198"  
- name: PROD_DEVELOPER_ACCOUNT_ID
  required: false
  value: "3"
- name: DISABLE_TLS_VALIDATION
  value: "yes"
- name: APPLICATION_NAME
  value: "my-app"
  required: true
- name: OPENAPI_SPECIFICATION_FILE
  required: true
  value: 'echo-api.json'
- name: TOOLBOX_IMAGE_REGISTRY
  required: true
  value: "quay.io/redhat/3scale-toolbox:latest"